flags: {}
packages:
  - '.'
  - extra-dep: true
    location:
      git: https://github.com/nomeata/inspection-testing.git
      commit: 0804c708092fed595dc4650afdd048dc1234ea4d

extra-deps: []
resolver: lts-11.9
